<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'Ars\\AlejandroDemoSeite\\' => array($typo3InstallDir . 'typo3conf/ext/alejandro_demo_seite/Classes'),
    'BK2K\\BootstrapPackage\\' => array($typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes'),
);
